const foods = ["APPLE","LEMON","CABBAGE","PASTA","EGG","LASAGNA","SAUSAGE","AVOCADO"]
const words = {
    easy: ["APPLE","NOSE","CAT","LEMON","MOTHER","CABBAGE","HOME","PASTA","BOOK","EGG","DOG","LASAGNA","GARDEN","HORSE","PAPER","MILK","EYE","CHICKEN","SNOW","WATER","LETTER","FLOWER","CHAIR","BABY","CHRISTMAS","HAPPY","FRIEND"],
    medium:["AQUATIC","KANGAROO","ALCOHOL","BUSINESS","FREEDOM","NEIGHBOR","PLANET","STOMACH","MARKET","INTERVIEW","CELEBRATION","GRAVE","SHRIMP","COUNTRY","SMILE","USEFUL","TELEPHONE","PANCAKE","RESTAURANT","SINGLE","DANGEROUS","LEOPARD","POLAR BEAR",],
    hard:["VIRTUAL","EMPATHY","GARENUK","MARGARINE","IRONY","PANGOLIN","HAM","SYNTAX","OTTER","CLANDESTINE","HIPPOPOTAMUS","PRESAGE","KEBAB","HOLISTIC","PARADOX","ALBATROSS","SATIRE","YOUNG ADULT"]
}
export {foods}