
const words = {
    easy: ["APPLE","NOSE","CAT","SHOULDERS","LEMON","MOTHER","HAT","CABBAGE","HOME","PASTA","BOOK",
    "EGG","DOG","COAT","LASAGNA","GARDEN","HORSE","PAPER","BIRD","MILK","SMOKE","COW","EYE","BREAD","CHICKEN","SNOW","SHOES","WATER","LETTER","FLOWER","CHAIR","BABY","HAPPY","FRIEND","ACTOR","JUICE","LADY","RAIN"],

    medium:["AQUATIC","EVIDENT","DIVERSITY","KANGAROO","ALCOHOL","BUSINESS","FREEDOM","NEIGHBOR","PLANET",
    "STOMACH","MARKET","INTERVIEW","PHENOMENON","CELEBRATION","GRAVE","SHRIMP","TRIVIA","COUNTRY","SMILE","USEFUL","TELEPHONE","PANCAKE","LEGACY","RESTAURANT","SINGLE","DANGEROUS","LEOPARD","POLAR BEAR","MACHINE","SILENCE"],

    hard:["VIRTUAL","EMPATHY","MARGARINE","IRONY","HAM","SYNTAX","OTTER","CLANDESTINE","OGRE","PRESAGE","HOLISTIC","PARADOX","SATIRE","YOUNG ADULT","REFLECTION","SCIENCE","AMBIVALENT","PARADIGM",
"CALUMNY","UBIQUITOUS","APATHETIC","NEGLIGENT","VOCIFEROUS","STATE","RHYTHM"]
}
export {words}